/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#444748",
        "secondary-fixed-dim": "#61dbb4",
        "on-primary-fixed-variant": "#474646",
        "surface-dim": "#ddd9d8",
        "border-subtle": "#E8E8E8",
        "on-surface": "#1c1b1b",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#858383",
        "text-tertiary": "#9E9E9E",
        "primary-fixed-dim": "#c9c6c5",
        "secondary-container": "#7cf5cc",
        "surface-canvas": "#FFFFFF",
        "surface-container-high": "#ebe7e6",
        "on-secondary-container": "#007056",
        "on-error": "#ffffff",
        "on-tertiary-container": "#868381",
        "inverse-surface": "#313030",
        "inverse-primary": "#c9c6c5",
        "on-secondary-fixed": "#002117",
        "primary": "#000000",
        "inverse-on-surface": "#f4f0ef",
        "text-secondary": "#6B6B6B",
        "outline-variant": "#c4c7c7",
        "background": "#fdf8f8",
        "primary-container": "#1c1b1b",
        "secondary-fixed": "#7ff8cf",
        "on-background": "#1c1b1b",
        "on-primary": "#ffffff",
        "tertiary": "#000000",
        "tertiary-fixed": "#e6e1df",
        "surface-container-highest": "#e5e2e1",
        "error-container": "#ffdad6",
        "surface-container-low": "#f7f3f2",
        "surface-variant": "#e5e2e1",
        "surface-bright": "#fdf8f8",
        "on-secondary": "#ffffff",
        "tertiary-container": "#1d1b1a",
        "secondary": "#006c52",
        "surface-tint": "#5f5e5e",
        "on-primary-fixed": "#1c1b1b",
        "on-tertiary-fixed-variant": "#484645",
        "on-tertiary-fixed": "#1d1b1a",
        "surface-container": "#f1edec",
        "on-secondary-fixed-variant": "#00513d",
        "outline": "#747878",
        "surface-soft": "#F5F5F5",
        "primary-fixed": "#e5e2e1",
        "tertiary-fixed-dim": "#cac6c3",
        "text-primary": "#1A1A1A",
        "surface": "#fdf8f8",
        "error": "#ba1a1a",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1200px",
        "md": "24px",
        "lg": "32px",
        "xs": "8px",
        "base": "8px",
        "sm": "16px",
        "xl": "48px"
      },
      fontFamily: {
        "nav-item": ["Inter", "sans-serif"],
        "meta-data": ["Inter", "sans-serif"],
        "section-title": ["Inter", "sans-serif"],
        "body-main": ["Inter", "sans-serif"],
        "card-title": ["Inter", "sans-serif"],
        "hero-title": ["Inter", "sans-serif"]
      },
      fontSize: {
        "nav-item": ["14px", { lineHeight: "1.0", fontWeight: "500" }],
        "meta-data": ["13px", { lineHeight: "1.4", fontWeight: "400" }],
        "section-title": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-main": ["15px", { lineHeight: "1.6", fontWeight: "400" }],
        "card-title": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "hero-title": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
